Server/basicapp/urls.py
from django.contrib.auth import views
from django.urls import path
from basicapp import views

# SET THE NAMESPACE!
app_name = 'basicapp'


urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home,name='home'),
    path('scan/', views.scan,name='scan'),
    path('nmapscan/', views.nmapscan,name='nmapscan'),
    path('nmapview/',views.view_nmap,name='nmapview'),
    path('pcapview/',views.view_pcap,name='pcapview'),
    path('downloadpage/',views.download_cap,name='form_download'),
    path('scandownload/',views.scan_download_pcap,name='form_scan'),
    path('nmapdownload/',views.download_nmap,name='form_nmap'),
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('download/', views.download_pcap,name='download'),
    path('userform/', views.showform,name='newform'),
    path('client_home/',views.client_home,name='client_home'),
    path('client/',views.client,name='client'),
    path('client_show/',views.client_show,name='client_show'),
    path('edit/<int:id>',views.client_edit,name='client_edit'),
    path('update/<int:id>',views.client_update,name='client_update'),
    path('delete/<int:id>',views.client_delete,name='client_delete'),

]

Server/basicforms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from basicapp import views
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)


urlpatterns = [
    path('', views.index,name='index'),
    path('admin/', admin.site.urls),
    path('special/', views.special,name='special'),
    path('basicapp/', include('basicapp.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('api-auth/', include('rest_framework.urls')),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

Server/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        {# Django Home Link / Register Link#}
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:register' %}">Register</a>

        {# Some logic on what to display for last item#}
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
          <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
        {% endif %}
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

Server/templates/base2.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        {# Django Home Link #}
        <a class="navbar-brand" href="{% url 'index' %}">Allitson</a>
     

        {# Some logic on what to display for last item#}
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
          <a class="nav-link" href="{% url 'basicapp:user_login' %}">Login</a>
        {% endif %}
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

Server/templates/client_edit.html
{% extends "base2.html" %}
{% block body_block %}



<form method="POST" class="post-form" action="/basicapp/update/{{client.id}}">
		{% csrf_token %}

	<div class="container">
		<br>
		<div class="form-group row">
		<label class="col-sm-1 col-form-lable"></label>	
			<div class="col-sm-4">
				<h3>Update Details</h3>
			</div>
		</div>
	

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Client ID : </label>
			<div class="col-sm-4">
				<input type="text" name="client_id" id="client_id" value="{{ client.client_id }}"/>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Client Name : </label>
			<div class="col-sm-4">
				<input type="text" name="client_name" id="client_name" value="{{ client.client_name }}"/>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Client Email : </label>
			<div class="col-sm-4">
				<input type="text" name="client_email" id="client_email" value="{{ client.client_email }}"/>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Client Contact : </label>
			<div class="col-sm-4">
				<input type="text" name="client_contact" id="client_contact" value="{{ client.client_contact }}"/>
			</div>
		</div>
		<button type="submit" class="btn btn-success">Update</button>
	</div>

{% endblock %}

Server/templates/client_home.html
{% extends "base2.html" %}
{% block body_block %}



	<ul>
		<li><a href="/basicapp/client_home" class="btn btn-primary">Home</a></li>
		<li><a href="/basicapp/client" class="btn btn-primary">Add New Record</a></li>
		<li><a href="/basicapp/client_show" class="btn btn-primary">Show</a></li>
	</ul>

<p>
<a href="{{request.META.HTTP_REFERER}}">Go back</a>
</p>
{% endblock %}

Server/templates/client_index.html
{% extends "base2.html" %}
{% block body_block %}

<form method="POST" class="post-form" action="/basicapp/client/">
		{% csrf_token %}

	<div class="container">
		<br>
		<div class="form-group row">
		<label class="col-sm-1 col-form-lable"></label>	
			<div class="col-sm-4">
				<h3>Enter Details</h3>
			</div>
		</div>
	

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Client ID : </label>
			<div class="col-sm-4">
				{{ form.client_id }}
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Client Name : </label>
			<div class="col-sm-4">
				{{ form.client_name }}
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Client Email : </label>
			<div class="col-sm-4">
				{{ form.client_email }}
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable"> Client Contact : </label>
			<div class="col-sm-4">
				{{ form.client_contact }}
			</div>
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>

</form>

{% endblock %}

Server/templates/client_show.html
{% extends "base2.html" %}
{% block body_block %}
<nav class="navbar navbar-light bg-light justify-content-between">
  <a class="navbar-brand">Client Record</a>
  <form class="form-inline">
 <div class="input-group">
                            <input name="q" type="text" placeholder="Search" class="form-control form-control-lg" />
                            <div class="input-group-append">

    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>

	<div class="container">
	<table class="table table-striped table-bordered table-sm">
		<thead class="thead-dark">
			<tr>
				<th>Client ID</th>
				<th>Client Name</th>
				<th>Client Email</th>
				<th>Client Contact</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for client in clients %}
			<tr>
				<td>{{ client.client_id }}</td>
				<td>{{ client.client_name }}</td>
				<td>{{ client.client_email }}</td>
				<td>{{ client.client_contact }}</td>
				<td>
					<a href="/basicapp/edit/{{ client.id }}"><span class="glyphicon glyphicon-pencil">Edit</span></a> | 
					<a href="/basicapp/delete/{{ client.id}}">Delete</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	<center><a href="/basicapp/client" class="btn btn-primary">Add New Record</a></center>
</div>

<nav aria-label="Page navigation example">
<div class="pagination">
    <span class="step-links">
        {% if clients.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ clients.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ clients.number }} of {{ clients.paginator.num_pages }}.
        </span>

        {% if clients.has_next %}
            <a href="?page={{ clients.next_page_number }}">next</a>
            <a href="?page={{ clients.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


</nav>

<p>
<a href="{{request.META.HTTP_REFERER}}">Go back</a>
</p>

{% endblock %}

<div class="pagination">
    <span class="step-links">
        {% if clients.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ clients.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ clients.number }} of {{ clients.paginator.num_pages }}.
        </span>

        {% if clients.has_next %}
            <a href="?page={{ clients.next_page_number }}">next</a>
            <a href="?page={{ clients.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>



    <li class="page-item"><a class="page-link" href="{{clients.previous_page_link}}">Previous</a></li>

{{ client.id}}

      <ul class="pagination">
            {% if clients.has_previous %}
            <li class="page-item"> <a href="?page=1" class="page-link"><< First</a> </li>
            <li class="page-item"><a href="{{clients_obj.previous_page_link}}" class="page-link">< Previous</a></li>
            {% endif %}
            {% if clients.has_next %}
            <li class="page-item"><a href="?page={{clients_obj.next_page_number}}" class="page-link">Next ></a></li>
            <li class="page-item"><a href="?page={{clients_obj.paginator.num_pages}}" class="page-link">Last >></a>
            </li>
            {% endif %}
        </ul> 


<ul class="pagination">
            {% if clients.has_previous %}
    <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
    <li class="page-item"><a class="page-link" href="{{clients.previous_page_link}}">Previous</a></li>
{% endif %}
            {% if clients.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{clients.next_page_number}}">Next</a></li>
    <li class="page-item"><a class="page-link" href="?page={{clients.paginator.num_pages}}">Last</a></li>
{% endif %}
 </ul>

Server/templates/home.html
{% extends "base2.html" %}
{% block body_block %}

    <div class="container">
      <div class="jumbotron">
      <h2 >Select a date to view the capture data!</h2>
       
              <form method="post" action="" id="cap_date" >
 
                {% csrf_token %}
               <label for="cap_date"> Select the Date: </label>
	        <input id="cap_date" type="date" name="cap_date">
                </p>
                 <label for="cap_loc">Choose your device from the list:</label>
               <select name="cap_loc" id="cap_loc">
                {% for i in devicelocation %}
                <option> {{i.0}} </option>
               {% endfor %}
              </select>
               </p>
               
         	<input type="submit" value="Submit">
                </form>

        </p>
              <form method="post" action="/basicapp/download/" id="cap_id" >
              {% csrf_token %}
	      <label for="cap_id">Choose a capture ID and download:</label>
              <select type="radio" id="cap_id" name="cap_id">
               {% for i in datacapture %}
               <option> {{i.0}} </option>
               {% endfor %}
               </select>
              <input id="cap_id" type="submit" class="btn btn-danger"  value="Download">
<p>
<a href="{{request.META.HTTP_REFERER}}">Go back</a>
</p>             
              
      </div>
    </div>
     
   
{% endblock %}
   

Server/templates/index.html
{% extends "base2.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Allitson Technologies</h1>
              {% csrf_token %}

    {% if user.is_authenticated %}
        <h2>Welcome {{ user.username }}!</h2>
         </p>
        <a class="display-4" href="{% url 'basicapp:home' %}">Wireshark Data capture</a>
        </p>
        <a class="display-4" href="{% url 'basicapp:scan' %}">Wireshark Scan </a>
         </p>
        <a class="display-4" href="{% url 'basicapp:nmapscan' %}">Nmap Scan </a>
          </p>
        <a class="display-4" href="{% url 'basicapp:client_home' %}">Allitson New Client Registration </a>
         <p>
      
    {% else %}
        <h2>Welcome to the site!</h2>
    {% endif %}
  </div>
</div>

{% endblock %}




<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Fluid jumbotron</h1>
    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
  </div>
</div>

Server/templates/login.html
{% extends 'base2.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'basicapp:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

Server/templates/newuserform.html
{% extends "base2.html" %}
{% block body_block %}


 <div class="container">
      <div class="jumbotron">  
<title>New User Registration Form</title>  

<body>  
<form method="POST" class="post-form" action="#">  
{% csrf_token %}  
<div class="container">  
<div class="form-group">
	<label for="username" class="control-label col-sm-2">Client Name</label>
	<div class="col-sm-10">
	<input type="text" name="username" value=""/>
	</div>
</div> 
<div class="form-group">
	<label for="email" class="control-label col-sm-2">Email</label>
	<div class="col-sm-10">
	<input type="text" name="email" value=""/>
	</div>
</div> 
<div class="form-group">
	<label for="contact" class="control-label col-sm-2">Contact</label>
	<div class="col-sm-10">
	<input type="text" name="contact" value=""/>
	</div>
</div> 
<div class="form-group">
	<label for="userid" class="control-label col-sm-2">Client Id</label>
	<div class="col-sm-10">
	<input type="text" name="userid" value=""/>
	</div>
</div> 
<div class="form-group">
<button type="submit" class="btn btn-default">Submit</button> 
</div>
</div> 

 </div>
    </div>
{% endblock %}

Server/templates/nmap_scan.html
{% extends "base2.html" %}
{% block body_block %}
{% load render_table from django_tables2 %}

    <div class="container">
      <div class="jumbotron">
      <h2 >NMAP Scan!</h2>

              <form method="post" action= "" id ="dev_loc" >

                {% csrf_token %}

                </p>
                 <label for="dev_loc">Choose your device from the list:</label>
               <select name="dev_loc" id="dev_loc">
                {% for i in devicelocation %}
                <option> {{i.0}} </option>
               {% endfor %}
              </select>
              </p>
             <input type="submit" value="Submit">

              
                 </form>
	     

		</p>  

             <p>Interface Name & IP Address </p>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Interface 1</th>
      <th scope="col">Interface 2</th>
      <th scope="col">Interface 3</th>

    </tr>
  </thead>
  <tbody>

    <tr>

      <th scope="row">Interface Name</th>
                 {% for i in Interface_name %}
      <td>{{i.0}}</td>
          {% endfor %}

    </tr>

    <tr>

      <th scope="row">IP Address</th>
           {% for i in Interface_name %}

      <td>{{i.1}}</td>
          {% endfor %}

    </tr>

  </tbody>
</table>
</p>
              <form method="post" action= "" id ="nmapip" >
              {% csrf_token %}


               </p>
               <label for="dev_loc">Choose your device from the list:</label>
               <select name="dev_loc" id="dev_loc">
                {% for i in devicelocation %}
                <option> {{i.0}} </option>
               {% endfor %}
              </select>
                <label for="nmapip">Enter the IP Address:</label><br>
                 <input type="text" id="nmapip" name="nmapip" ><br>
                 <label for="nmapsubnet">Enter Subnet Value:</label><br>
                 <input type="text" id="nmapsubnet" name="nmapsubnet" >
                <input type="submit" value="Submit">
                </form>

        </p>


              <form method="post" action="/basicapp/nmapdownload/" id="nmapip" >
              {% csrf_token %}


              <p> Download the Nmap ID number {{ datacapture }}</p>


              <input id="" type="submit" class="btn btn-danger"  value="Download">

              </form>
             </p>
              <form method="post" action="/basicapp/nmapview/" id="" >
              {% csrf_token %}


              <input id="" type="submit" class="btn btn-danger"  value="View">

              </form>
<p>
<a href="{{request.META.HTTP_REFERER}}">Go back</a>
</p>
      </div>
    </div>



{% endblock %}


                    <option value = "{{results.name}}">{{results.name}}</option>

</p>
              <form method="post" action= "" id ="nmapip" >
              {% csrf_token %}


               </p>
                <label for="nmapip">Enter the IP Address:</label><br>
                 <input type="text" id="nmapip" name="nmapip" ><br>
                 <label for="nmapsubnet">Enter Subnet Value:</label><br>
                 <input type="text" id="nmapsubnet" name="nmapsubnet" >
                <input type="submit" value="Submit">
                </form>

        </p>

Server/templates/registration.html
{% extends "base2.html" %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

Server/templates/scan.html
{% extends "base2.html" %}
{% block body_block %}

    <div class="container">
      <div class="jumbotron">
      <h2 >Select a date to view the capture data!</h2>

              <form method="post" action= "" id ="cap_sec" >

                {% csrf_token %}
               
                </p>
                 <label for="dev_loc">Choose your device from the list:</label>
               <select name="dev_loc" id="dev_loc">
                {% for i in devicelocation %}
                <option> {{i.0}} </option>
               {% endfor %}
              </select>
               </p>
                <label for="cap_sec"> Enter the capture duration(Secs): </label>
                <input id="cap_sec" type="number" name="cap_sec">

                <input type="submit" value="Submit">
                </form>

        </p>

              <form method="post" action="/basicapp/scandownload/" id="" >
              {% csrf_token %}
          
              <p> Download the Capture ID number {{ datacapture }}</p>

       
              <input id="" type="submit" class="btn btn-danger"  value="Download">

              </form>

   </p>

              <form method="post" action="/basicapp/pcapview/" id="" >
              {% csrf_token %}


              <input id="" type="submit" class="btn btn-danger"  value="View">

              </form>    
<p>
<a href="{{request.META.HTTP_REFERER}}">Go back</a>
</p>
 
 </div>
    </div>


{% endblock %}



<a href="link/to/your/download/file" download>Download link</a>
<form method="post" action="/basicapp/download/" id="cap_id" >
              {% csrf_token %}
              <label for="cap_id">Choose a capture ID and download:</label>
              <select type="radio" id="cap_id" name="cap_id">
               <p> Capture ID Number is {{ datacapture }}</p>
               {% for i in datacapture %}
               <option> {{i.0}} </option>
               {% endfor %}
               </select>
              <input id="cap_id" type="submit" class="btn btn-danger"  value="Download">



profiles = Profiles.objects.all;
render_to_response('template.html', {'profiles': profiles })

{% for profile in profiles %}
      <p>{{ profile.first_name }}</p>
      <p>{{ profile.surname }}</p>
{% endfor %}

                <center><label for="abc">Input Text</label>
                <input type="text" name="input_text"class="form-group"   id="abc"placeholder="Text input">



<form method="post" action="/basicapp/download/" id="cap_id" >
              {% csrf_token %}
              <p>{{ datacapture }}</p>


              <input id="cap_id" type="submit" class="btn btn-danger"  value="Download">
              </form>